services:
  react-app:
    hostname: react-app
    image: node:latest
    user: node
    container_name: react_app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    volumes:
      - ${FE_APP_PATH}:/usr/src/app
    command: bash -c "npm install --ignore-scripts && npm run start"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
